# ZSH Configuration
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="pure"
plugins=(bower, composer, git, npm, symfony2)
source $ZSH/oh-my-zsh.sh

# User configuration
export PATH="/home/jevillard/bin:/home/jevillard/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

# Aliases
alias zshconfig="vim ~/.zshrc"
alias upgrade="sudo apt-get update && sudo apt-get -y -d dist-upgrade && sudo apt-get -y autoclean && sudo apt-get -y autoremove"
