# ZSH Configuration
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="refined"
plugins=(bower, composer, docker, git, npm, symfony2)
source $ZSH/oh-my-zsh.sh

# User configuration
export PATH="/home/jevillard/bin:/home/jevillard/.composer/vendor/bin:/home/jevillard/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

# Vim configuration
stty -ixon

# Aliases
alias ll="ls -alF  --color=auto"
alias zshconfig="vim ~/.zshrc"
alias upgrade="sudo apt-get update && sudo apt-get -y -d dist-upgrade --force-yes && sudo apt-get -y autoclean && sudo apt-get -y autoremove"